name: 'Group Dependabot PRs'
description: 'Combine openned dependabot PRs to easily test them'
inputs:
  combineBranchName:
    description: 'Name of the branch to combine PRs into'
    required: true
    default: 'combined-denpendabot-prs'
  combinePullRequestTitle:
    description: 'Title of the pull request to combine PRs into'
    required: true
    default: 'combined-denpendabot-prs'
  baseBranch:
    description: 'Branch to PR into'
    required: true
    default: 'master'
  githubToken:
    description: 'The GitHub token used to create an authenticated client'
    default: ${{ github.token }}
    required: true
runs:
  using: 'node12'
  pre: 'action/pre.js'
  main: 'index.js'
